services:
  web.typecho:
    image: nedvedliao/typecho:nginx-php7.3-fpm
    container_name: typecho
    hostname: typecho
    restart: always
    ports:
    - 80:80/tcp
    - 443:443/tcp
    volumes:
    #ssl setting
    #- ./nginx/certs:/etc/nginx/certs
    #- ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/html:/var/www/html
    networks:
    - front
    - back

  db.redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: always
    networks:
    - back

  db.mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    privileged: false
    restart: always
    ports:
    - 3306:3306
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=mysql_root_pass
    - MYSQL_DATABASE=typecho
    - MYSQL_USER=typecho
    - MYSQL_PASSWORD=mysql_typecho_pass
    networks:
    - back

networks:
  front:
    ipam:
      config:
      - subnet: 172.15.0.0/16

  back:
    ipam:
      config:
      - subnet: 172.25.0.0/16

version: '3.4'
